### Create user valid signature
POST http://127.0.0.1:8080/api/users
Authorization: Basic sp56708 123456
X-HMAC-SIGNATURE: 1844edf1903d5b818f88b1c392f2813fcce734c11c3cb5d44332a6539b2a3c7f
Content-Type: application/json

{
  "requestHeader": {
    "requestId": "2a4fc4ce-4e6f-4b04-8cea-7c0ae5031e27",
    "sendDate": "2020-11-17T12:08:56.235-0100"
  },
  "user": {
    "name": "Paweł",
    "surname": "Siwoń",
    "age": 90,
    "personalId": "01234567890",
    "citizenship": "DE",
    "email": "56708@zut.edu.pl"
  }
}

> {%
    client.global.set("userId", response.body.user.id);
%}

### Get auth token
POST https://pba-auth-server.herokuapp.com/oauth/token
Authorization: Basic pba_user 123456
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Get signature for payload
POST http://127.0.0.1:8080/api/signing
Authorization: Basic sp56708 123456
Content-Type: application/json

{
  "requestHeader": {
    "requestId": "2a4fc4ce-4e6f-4b04-8cea-7c0ae5031e27",
    "sendDate": "2020-11-17T12:08:56.235-0100"
  },
  "user": {
    "name": "Paweł",
    "surname": "Noswak",
    "age": 90,
    "personalId": "92011165987",
    "citizenship": "DE",
    "email": "56708@zut.edu.pl"
  }
}

> {%
    client.global.set("jwts_signature", response.body.signature);
%}

### Update user with JWTS-SIGNATURE
PUT http://127.0.0.1:8080/api/users/{{userId}}
X-JWS-SIGNATURE: {{jwts_signature}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "requestHeader": {
    "requestId": "2a4fc4ce-4e6f-4b04-8cea-7c0ae5031e27",
    "sendDate": "2020-11-17T12:08:56.235-0100"
  },
  "user": {
    "name": "Paweł",
    "surname": "Nowak",
    "age": 90,
    "personalId": "92011165987",
    "citizenship": "DE",
    "email": "56708@zut.edu.pl"
  }
}